$defs:
  CollectionMethods:
    enum:
    - Modeling
    - Laboratory
    - Field
    title: CollectionMethods
    type: string
  Countries:
    enum:
    - Domestic (USA)
    - International
    title: Countries
    type: string
  Disciplines:
    enum:
    - Acoustics
    - Array Effects
    - Condition Monitoring
    - Control
    - Cost Assessment
    - Data Conversion
    - Data QA and QC
    - Deployment
    - Decommissioning
    - Electrical Network
    - Energy Storage
    - Environmental Impact
    - Extreme Events
    - Grid Integration
    - Hybrid Devices
    - Hydrodynamics
    - Instrumentation
    - Levelized Cost of Energy
    - Machine Learning
    - Manufacturing
    - Maritime Markets
    - Materials
    - Meshing
    - Mooring
    - Multibody Dynamics
    - Operations and Maintenance
    - Optimization
    - Performance
    - Power Take Off
    - Pre-Post Processing
    - Reliability
    - Safety and Security
    - Sediment Transport
    - Site Characterization
    - Standards
    - Structural
    - Substructure
    - Supply Chain
    - Survivability
    - Turbulence
    - Visualization
    title: Disciplines
    type: string
  FundingBodies:
    enum:
    - WPTO
    title: Funding Bodies
    type: string
  Interfaces:
    enum:
    - Graphical
    - Textual
    - web-API
    - Web Page
    title: Interfaces
    type: string
  LicenceTypes:
    enum:
    - Open-Source
    - Commercial
    - No License
    - Freemium
    - Freeware
    - Non-commercial
    - Government Use
    - Other
    title: LicenceTypes
    type: string
  LifeCyclePoints:
    enum:
    - Design
    - Manufacturing
    - Deployment
    - Condition Monitoring
    - Operations and Maintenance
    - Decommissioning
    title: LifeCyclePoints
    type: string
  Methods:
    enum:
    - Acoustic Wave Equation
    - Actuator Line Method
    - Blade Element Momentum Theory
    - Boundary Element Method (BEM)
    - Boussinesq
    - Bubble Image Velocimetry (BIV)
    - Cable Routing
    - Cartesian Cut-Cell
    - Computational Fluid Dynamics (CFD)
    - Conservation Planning
    - Data Acquisition
    - Discrete Vortex Method
    - Distribution Management System (DMS)
    - Ecological Risk Assessment
    - Energy Balance
    - Environmental Contours
    - Euler Equations
    - Extreme Value Analysis
    - Finite Difference Method
    - Finite Element Analysis
    - Geographic Information System (GIS)
    - High-Order Spectral
    - Image Processing
    - Incompressible Navier-Stokes
    - Internet of Things (IoT)
    - Inverse First-Order Reliability Method
    - Jensen's Wake Model
    - Large Eddy Simulation (LES)
    - Life Cycle Assessment
    - Linear Wave Theory
    - Logistics
    - Lumped Mass Method (LMM)
    - Marine Spatial Planning (MSP)
    - Maximum Likelihood Estimation
    - Mechanics
    - Modal Analysis
    - Moment Matching
    - Motion Detection
    - Multipole Expansion
    - Natural Language Processing (NLP)
    - Optical Flow
    - Optimal Power Flow
    - Optimization
    - Panel Method
    - Particle Image Velocimetry (PIV)
    - Potential Flow
    - Primitive Equations
    - Pseudo-Spectral
    - Particle Tracking Velocimetry (PTV)
    - Quasi-Static Loads
    - Robotics Middleware
    - SCADA
    - Shallow Water Equations
    - Shape Analysis
    - Smoothed-Particle Hydrodynamics (SPH)
    - State Space
    - Static Loads
    - Statistics
    - Stream Function
    - Subsurface Science
    - Tidal Harmonics
    - Verification and Validation
    - Vortex Lattice Method (VLM)
    - Vortex Particle Method (VPM)
    - Vorticity Transport Equation
    - Wave Spectral Analysis
    - Wind Wave Model
    title: Methods
    type: string
  OSLicenceModel:
    properties:
      Open-Source:
        anyOf:
        - items:
            $ref: '#/$defs/OpenSourceOptions'
          type: array
          uniqueItems: true
        - type: 'null'
        default: null
        description: A type of license that allows the software's source code and/or
          binaries to be used, modified and/or shared under defined terms and conditions.
        title: Open-Source
    title: OSLicenceModel
    type: object
  OpenSourceOptions:
    enum:
    - GPL
    - LGPL
    - AGPL
    - CeCILL
    - MIT
    - BSD
    - Apache
    - The Unlicense
    - Other
    title: OpenSourceOptions
    type: string
  PrimaryUses:
    enum:
    - Marine Renewable Energy
    - Naval Architecture
    - Ocean and Coastal Engineering
    - Offshore Oil and Gas
    - Offshore Wind
    - Other
    title: PrimaryUses
    type: string
  ProgrammingLanguages:
    enum:
    - C
    - C++
    - Fortran
    - Java
    - JavaScript
    - MATLAB
    - Python
    - R
    - Other
    title: ProgrammingLanguages
    type: string
  TRLs:
    enum:
    - 1-3
    - 4-6
    - 7-9
    title: TRLs
    type: string
  Technologies:
    enum:
    - Wave
    - Current
    - OTEC
    - Salinity Gradient
    - Other
    title: Technologies
    type: string
additionalProperties: false
description: This is the schema for the MRE software database, written using JSON
  Schema.
properties:
  Collection Method:
    description: Point of use of the software package, i.e. the physical source of
      data transformed by the software.
    items:
      $ref: '#/$defs/CollectionMethods'
    title: Collection Method
    type: array
    uniqueItems: true
  Country of Origin:
    anyOf:
    - items:
        $ref: '#/$defs/Countries'
      type: array
      uniqueItems: true
    - type: 'null'
    default: null
    description: Countries from which the software originates. Particularly useful
      if the software is only licensed for use within a designated territory.
    title: Country Of Origin
  Dependencies:
    anyOf:
    - type: string
    - items:
        type: string
      type: array
      uniqueItems: true
    - type: 'null'
    default: null
    description: Major dependencies and add-on packages of the software package, e.g.
      for pre- and post-processing.
    title: Dependencies
  Description:
    anyOf:
    - type: string
    - type: 'null'
    default: null
    description: The description of the software package.
    title: Description
  Developer:
    anyOf:
    - type: string
    - type: 'null'
    default: null
    description: The name of the software developer, e.g. company, research body,
      individual.
    title: Developer
  Discipline:
    anyOf:
    - items:
        $ref: '#/$defs/Disciplines'
      type: array
      uniqueItems: true
    - type: 'null'
    default: null
    description: Applicable disciplines or functionalities of the software package.
    title: Discipline
  Funding:
    anyOf:
    - items:
        $ref: '#/$defs/FundingBodies'
      type: array
      uniqueItems: true
    - type: 'null'
    default: null
    description: Sources of funding received for the software package.
    title: Funding
  Interface:
    anyOf:
    - items:
        $ref: '#/$defs/Interfaces'
      type: array
      uniqueItems: true
    - type: 'null'
    default: null
    description: The means by which the user interacts with the software.
    title: Interface
  License Type:
    anyOf:
    - items:
        anyOf:
        - $ref: '#/$defs/LicenceTypes'
        - $ref: '#/$defs/OSLicenceModel'
      type: array
      uniqueItems: true
    - type: 'null'
    default: null
    description: The types, if any, of license governing use and development of the
      software.
    title: License Type
  Life Cycle:
    description: Applicable marine renewable energy technology life cycle phases for
      the software package.
    items:
      $ref: '#/$defs/LifeCyclePoints'
    title: Life Cycle
    type: array
    uniqueItems: true
  Method:
    anyOf:
    - items:
        $ref: '#/$defs/Methods'
      type: array
      uniqueItems: true
    - type: 'null'
    default: null
    description: Underlying theory or method of the software package.
    title: Method
  Note:
    description: Additional notes relating to the package.
    title: Note
    anyOf:
    - type: string
    - type: 'null'
    default: null
  Primary Use:
    description: The primary technologies applicable to the software package.
    items:
      $ref: '#/$defs/PrimaryUses'
    title: Primary Use
    type: array
    uniqueItems: true
  Programming Language:
    anyOf:
    - items:
        $ref: '#/$defs/ProgrammingLanguages'
      type: array
      uniqueItems: true
    - type: 'null'
    default: null
    description: Programming languages used to create (or operate) the software package.
    title: Programming Language
  TRL:
    description: Applicable technology readiness level (TRL) ranges of the technology
      supported by the software package.
    items:
      $ref: '#/$defs/TRLs'
    title: TRL
    type: array
    uniqueItems: true
  Technology:
    description: Marine renewable energy (MRE) technologies applicable to the software
      package.
    items:
      $ref: '#/$defs/Technologies'
    title: Technology
    type: array
    uniqueItems: true
  Title:
    description: The name of the software package.
    title: Title
    type: string
  Web Address:
    anyOf:
    - type: string
    - type: 'null'
    default: null
    description: The URL of the software package.
    title: Web Address
required:
- Title
- Primary Use
- Technology
- TRL
- Collection Method
- Life Cycle
title: MRE Software Database Schema
type: object
