name: format
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  format:
    if: ${{ github.repository_owner == 'MRE-Code-Hub' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Format records
        run: python format.py format
      - name: Commit changes
        if: github.repository_owner == 'MRE-Code-Hub' && github.event_name != 'pull_request'
        uses: stefanzweifel/git-auto-commit-action@v5
  template:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Gerate template
        run: python format.py template
      - name: Commit changes
        if: github.repository_owner == 'MRE-Code-Hub' && github.event_name != 'pull_request'
        uses: stefanzweifel/git-auto-commit-action@v5
